version: '3.8'

services:
  app:
    image: roxburghm/sudoku
    build:
      context: .
      dockerfile: Dockerfile
      args:
        repo: github.com/roxburghm/vue-sudoku

    ports:
      - 8502:8080
