name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/roxburghm/vue-sudoku:latest .
          docker push ghcr.io/roxburghm/vue-sudoku:latest
